### ISSUE TITLE
separate pmix and openpmix bits

### ISSUE THREAD

**Issue by naughtont3** [pmix/pmix.github.io#10]
Separate the content that is related to PMIx Forum (standard) from the OpenPMIx (implementation) pieces.  I will do same setup for openpmix.github.io, using "dark" theme for distinction (probably with different logo) and place the implementation bits in there.

**Comment by naughtont3** [comment]
I created a slightly different version using content from here for the implementation page at https://openpmix.github.io/


Note, it appears the minimal "dark" theme is not fully released and I could not easily just switch over as I'd hoped.  To avoid confusion, I used a different theme 'modernist' so things look even more different.  I had to tweak a few things manually that were sort of ugly in default.html to get layout i wanted but good enough for now.  

I also noticed that some of the params at top of .md files were specific to minima theme and caused problem with 'modernist' theme (namely: `layout: page` and `permalink: /xyz`). So I removed the permalink bit and change other to `layout: deafult`.  Other tweaks were to get heading links at top and Copyright stamp in footer.  

Both of those are easier to modify in minima theme, but did not want to have same appearance and confuse people between pmix.github.io and openpmix.github.io.

**Comment by rhc54** [comment]
I think this looks really nice - very distinctive!

**Comment by naughtont3** [comment]
Thanks @rhc54.  I started to pull other bits out to further separate content in #11.  It also adds a top-level "Meeting" item to the pages, which seems like the main point for the Standard pages.

Not sure what to do with Publications, but in general I do not think we want the same content in both pmix and openpmix github.io sites.

Excluding the Pubs item, i think #11 should have a decent split of things and possibly call things "done" (at least for migration/standup phase).

**Comment by rhc54** [comment]
I think the pubs that describe the concept (e.g., the one we suggest for citations) should probably be on both sites. The rest of the paper publications should go to the openpmix site.

Presentations are a trickier question.I can try to take a pass on them. Some deal with concepts (e.g., describing event notification in general) while others dive into implementation. May not be able to cleanly separate them, but I'll give it a try.

**Comment by naughtont3** [comment]
OK, I did some chopping and shuffling of things.  I chopped papers from PMIx page and added pointer to OpenPMIx Pubs.  I'll leave presentations on both for the moment.  We can decide where those make most sense later.  

I also changed the header links a bit for PMIx site to have the Standard page at top and removed the Download page (which for Standard site is pretty vacant).

**Comment by naughtont3** [comment]
I also drop the flow diagram from PMIx site, so Standard just has the logo.  and OpenPMIx has flow diagram.  But both have some graphic at top of landing page.

**Comment by naughtont3** [comment]
We've made an initial pass at this, so calling this done. We can refine as needed going forward.
