### ISSUE TITLE
pmix.org domain redirect

### ISSUE THREAD

**Issue by naughtont3** [pmix/pmix.github.io#14]
Once the pmix.github.io is considered "done", we need to update the DNS pointer for pmix.org to point to the new location.

**Comment by SteVwonder** [comment]
Is there any tasks blocking pmix.github.io from being considered "good enough" to start the domain redirect?  AFAICT, all of the content has been transferred over, and any work that remains is trimming/iterating on the existing content.

Any opposition to changing the DNS and going live now?

**Comment by rhc54** [comment]
I don't think so - I think it is mainly just me modifying the DNS entry for pmix.org. I can try to look at doing that sometime today/tomorrow.

**Comment by rhc54** [comment]
Okay, it should now be forwarded, but may take a while to propagate (they say up to 24 hours for https to update)

**Comment by rhc54** [comment]
Unfortunately, it appears that pmix.org may be down during the transition...sigh. Will have to keep an eye on it.

**Comment by rhc54** [comment]
Okay, redirection accomplished! @SteVwonder @naughtont3 We should add a prominent note on the main page of pmix.github.io explaining what has happened so that people aren't totally blown away when the familiar main page doesn't appear.

**Comment by rhc54** [comment]
And the Wordpress site has been taken down...
