### ISSUE TITLE
Migrate contribute page from pmix.org

### ISSUE THREAD

**Issue by SteVwonder** [pmix/pmix.github.io#3]
Migrate the subset of the contribute page relevant to the standard (with links to OpenPMIx, PRRTE, etc): https://pmix.org/contribute/

**Comment by naughtont3** [comment]
For now, I'm just do wholesale migrate to Markdown.  Then after the pmix.org is in place in new format, it will be easier to chop up and will copy over to openpmix version of same setup w/ slightly different colors/theme.
