### ISSUE TITLE
create base gh pages for new pmix.org

### ISSUE THREAD

**Issue by naughtont3** [pmix/pmix.github.io#6]
Create the base structure for the migration of content to new [github project web page](https://pages.github.com) .  The other issues will need this to properly render content.

**Comment by naughtont3** [comment]
Creating starter branch for testing of quick copy over of content to GH site.  
 - https://github.com/naughtont3/pmix.github.io.git in branch `www-v1`

You can test `www-v1` branch locally by running the following from top-dir of branch checkout.
 - If needed, install/setup Ruby 

 - Start localhost server to view/edit content
```
  bundle exec jekyll serve
```
 - Browse http://127.0.0.1:4000

 - Refs
     - https://jekyllrb.com/docs/installation/macos
    - https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll#creating-your-site

 - FWIW, here are  some notes [STEPS.txt](https://github.com/pmix/pmix.github.io/files/4594308/STEPS.txt) for what I did during setup on my mac.

**Comment by naughtont3** [comment]
Switched to another branch with compressed PDFs to avoid overly large files in Git.
 - `www-v2` branch

**Comment by naughtont3** [comment]
working through rest of content.  i did a scrape of pmix.org, so I can see content in filesystem.  will finish wp/html to md and then chop things up into pmix and openpmix sites.

**Comment by naughtont3** [comment]
OK, all content from current site, with exception of  couple feeds/posts, have been migrated to entirely Markdown format.  You can check things out in the 'www-v2' branch.
 - https://github.com/naughtont3/pmix.github.io/tree/www-v2

**Comment by naughtont3** [comment]
One more note, we could use the `dark` mode for the OpenPMIX site so they look similar but different.

Here are the changes to run [minima theme with the `dark` mode](https://blog.slowb.ro/dark-theme-for-minima-jekyll/).
 - Edit Gemfile changing 'minima' to point to latest git version

  ```
    #gem "minima", "~> 2.5"
    gem "minima", git: "https://github.com/jekyll/minima"
  ```
   - NOTE: I also had to comment out the `github-pages` b/c it had older dependency

 - Rerun bundle install/update
 ```
   bundle install && bundle updated
 ```

 - Edit _config.yml (adding below)

  ```
  minima:
    skin: dark
    #skin: classic
    #skin: solarized
    #skin: solarized-dark
  
```

Examples:
 - "Classic" theme [screencap-classic](https://user-images.githubusercontent.com/5482161/81772389-b1b97680-94b3-11ea-8503-00bb3c13cb8d.png)
 - "Dark" theme  [screencap-dark](https://user-images.githubusercontent.com/5482161/81772413-bf6efc00-94b3-11ea-8daa-824d5a6d3e03.png)

**Comment by naughtont3** [comment]
For ticket trails, i used pandoc for wordpress html to markdown.  Only helps to get body/content formatted, but still need to do some manual steps.
 - [convert-pandoc-html2md.sh.txt](https://github.com/pmix/pmix.github.io/files/4619895/convert-pandoc-html2md.sh.txt)

**Comment by SteVwonder** [comment]
With the merging of #7, I think this is probably good to close.  @naughtont3 ?  Thanks again for all the work on this!
